### ISSUE TITLE
Set multiple TP/SL and Hedge Mode on Bybit

### ISSUE THREAD

**Issue by bloodrain88** [CryptoGnome/Bybit-Lick-Hunter-v4#17]
async function setPositionMode() {

    const set = await linearClient.setPositionMode({
        coin: "USDT",
        mode: "BothSide",
        tp_sl_mode: "Partial"
    });

**Comment by CryptoGnome** [comment]
Can you explain how you would like to use this?

**Comment by bloodrain88** [comment]
To prevent an order stay too much in position would be nice to update TP/SL based on trend or to add multiple TP/SL to the order

**Comment by CryptoGnome** [comment]
I don't see this being supported so am kindly closing this
