### ISSUE TITLE
discord setting bug

### ISSUE THREAD

**Issue by jakkapong1129** [CryptoGnome/Bybit-Lick-Hunter-v4#19]
I setting USE_DISCORD = false, but bot send msg to discord all time

**Comment by Chan-TH** [comment]
you can deleted url here for help 
DISCORD_URL = https://discord.com/api/webhooks..........(deleted your discord webhook url)

**Comment by jakkapong1129** [comment]
If delete DISCORD_URL it will get an error.

**Comment by CryptoGnome** [comment]
Can you show the error please?

**Comment by jakkapong1129** [comment]
![image](https://user-images.githubusercontent.com/60910772/214744411-18cd707e-fb3d-402f-b223-b685323fbedf.png)

**Comment by CryptoGnome** [comment]
Fixed pull the new version from github and this should be resolved!
